{
 "title": "Standard ClickHouse Count over DateTime column",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "number of connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(time), 1) * 1) * 1000 as t,\n    count()\nFROM default.kdd99_material\n\nWHERE time >= toDateTime(1625482888) AND time <= toDateTime(1625483788)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  },
  {
   "title": "count column in 2 sec paket-timeframe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(count, count(*) c)\nFROM kdd99_material\n",
     "rawQuery": "SELECT t, groupArray((count, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time), 1) * 1) * 1000 AS t, count, count(*) c FROM kdd99_material WHERE time >= toDateTime(1625483125) AND time <= toDateTime(1625484025) GROUP BY t, count ORDER BY t, count) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  },
  {
   "title": "protocol count TCP UDP ICMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(protocol, count(*) c)\nFROM kdd99_material\n",
     "rawQuery": "SELECT t, groupArray((protocol, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time), 1) * 1) * 1000 AS t, protocol, count(*) c FROM kdd99_material WHERE time >= toDateTime(1625483243) AND time <= toDateTime(1625484143) GROUP BY t, protocol ORDER BY t, protocol) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  },
  {
   "title": "dst and src IPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(dstIP, count(*) c) \nFROM kdd99_material\n",
     "rawQuery": "SELECT t, groupArray((dstIP, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time), 1) * 1) * 1000 AS t, dstIP, count(*) c FROM kdd99_material WHERE time >= toDateTime(1625483026) AND time <= toDateTime(1625483926) GROUP BY t, dstIP ORDER BY t, dstIP) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    },
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(srcIP, count(*) c) \nFROM kdd99_material\n",
     "rawQuery": "SELECT t, groupArray((srcIP, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time), 1) * 1) * 1000 AS t, srcIP, count(*) c FROM kdd99_material WHERE time >= toDateTime(1625483026) AND time <= toDateTime(1625483926) GROUP BY t, srcIP ORDER BY t, srcIP) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  },
  {
   "title": "dstPorts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(dstPort, count(*) c) \nFROM kdd99_material",
     "rawQuery": "SELECT t, groupArray((dstPort, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time), 1) * 1) * 1000 AS t, dstPort, count(*) c FROM kdd99_material WHERE time >= toDateTime(1625484077) AND time <= toDateTime(1625484977) GROUP BY t, dstPort ORDER BY t, dstPort) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  },
  {
   "title": "services by name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(service, count(*) c) \nFROM kdd99_material\n",
     "rawQuery": "SELECT t, groupArray((service, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(time), 1) * 1) * 1000 AS t, service, count(*) c FROM kdd99_material WHERE time >= toDateTime(1625484025) AND time <= toDateTime(1625484925) GROUP BY t, service ORDER BY t, service) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  },
  {
   "title": "sum of dstBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    sum(dstbytes) as sumdstbytes\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(time), 1) * 1) * 1000 as t,\n    sum(dstbytes) as sumdstbytes\nFROM default.kdd99_material\n\nWHERE time >= toDateTime(1625483925) AND time <= toDateTime(1625484825)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  },
  {
   "title": "sum of srcBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    sum(srcbytes) as sumsrcbytes\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(time), 1) * 1) * 1000 as t,\n    sum(srcbytes) as sumsrcbytes\nFROM default.kdd99_material\n\nWHERE time >= toDateTime(1625483769) AND time <= toDateTime(1625484669)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "kdd99_material"
    }
   ]
  }
 ]
}